### ISSUE TITLE
Topics list

### ISSUE THREAD

**Issue by talnicolas** [claudemamo/kafka-web-console#22]
Hi,

I managed to start the application after adapting a bit the evolutions scripts for the db, successfully registered one zookeepers but nothing appears in the on the Topics page.
Here's what I have in the logs:

> ! @6ii9ko0jf - Internal server error, for (GET) [/topics.json] ->
> 
> play.api.Application$$anon$1: Execution exception[[UnsupportedOperationException: > empty.head]]
>   at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.1.jar:2.2.1]
>   at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.1.jar:2.2.1]
>   at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10-2.2.1.jar:2.2.1]
>   at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10-2.2.1.jar:2.2.1]
>   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.2.jar:na]
>   at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library-2.10.2.jar:na]
> Caused by: java.lang.UnsupportedOperationException: empty.head
>   at scala.collection.immutable.Vector.head(Vector.scala:192) ~[scala-library-2.10.2.jar:na]
>   at common.Util$$anonfun$getPartitionsLogSize$2$$anonfun$apply$16$$anonfun$5.apply(Util.scala:56) ~[classes/:na]
>   at common.Util$$anonfun$getPartitionsLogSize$2$$anonfun$apply$16$$anonfun$5.apply(Util.scala:56) ~[classes/:na]
>   at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:253) [scala-library-2.10.2.jar:na]
>   at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249) [scala-library-2.10.2.jar:na]
>   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library-2.10.2.jar:na]

Do you know where the problem could come from?

**Comment by gayathrisowmya** [comment]
Can u let me know what was the fix to this issue. I am getting the same error now. Topics list is empty though I have topics and the error is as shown below

! @6mo1m620j - Internal server error, for (GET) [/topics.json] ->

play.api.Application$$anon$1: Execution exception[[UnsupportedOperationException: empty.head]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.1.jar:2.2.1]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.1.jar:2.2.1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10-2.2.1.jar:2.2.1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10-2.2.1.jar:2.2.1]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
Caused by: java.lang.UnsupportedOperationException: empty.head
	at scala.collection.immutable.Vector.head(Vector.scala:192) ~[scala-library.jar:na]
	at controllers.Topic$$anonfun$controllers$Topic$$getPartitionsLogSize$2$$anonfun$apply$26$$anonfun$26.apply(Topic.scala:239) ~[classes/:na]
	at controllers.Topic$$anonfun$controllers$Topic$$getPartitionsLogSize$2$$anonfun$apply$26$$anonfun$26.apply(Topic.scala:239) ~[classes/:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:253) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]
