### ISSUE TITLE
Topics list is empty

### ISSUE THREAD

**Issue by gayathrisowmya** [claudemamo/kafka-web-console#73]
I am getting this error when I go to the Topics section. The topics are not getting displayed. I am using the default database. Any input is appreciated.

! @6mo1m620j - Internal server error, for (GET) [/topics.json] ->

play.api.Application$$anon$1: Execution exception[[UnsupportedOperationException: empty.head]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.1.jar:2.2.1]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.1.jar:2.2.1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10-2.2.1.jar:2.2.1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10-2.2.1.jar:2.2.1]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
Caused by: java.lang.UnsupportedOperationException: empty.head
	at scala.collection.immutable.Vector.head(Vector.scala:192) ~[scala-library.jar:na]
	at controllers.Topic$$anonfun$controllers$Topic$$getPartitionsLogSize$2$$anonfun$apply$26$$anonfun$26.apply(Topic.scala:239) ~[classes/:na]
	at controllers.Topic$$anonfun$controllers$Topic$$getPartitionsLogSize$2$$anonfun$apply$26$$anonfun$26.apply(Topic.scala:239) ~[classes/:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:253) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]

**Comment by ddreggors** [comment]
I am seeing the same exact error on console and my topic list is also empty.

I am running Kafka 0.8.1.1 and zookeeper 3.4.6

**Comment by JasonMoke** [comment]
Often do not provide services，why？

**Comment by ddreggors** [comment]
Do you need something more JasonMoke?

What are you asking for with your above question, I can give more if you need something in particular.

**Comment by mikehomee** [comment]
I'm seeing this same error, any solution so far?
